version: "3.0"
services:
  discovery-server:
    build: 
      context: ./discovery-server/
      dockerfile: Dockerfile
    ports:
      - 4444:4444
  gateway-server:
    build:
      context: ./gateway-server/
      dockerfile: Dockerfile
    ports:
      - 5555:5555
    depends_on:
      - configuration-server
  configuration-server:
    build:
      context: ./configuration-server/
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    depends_on:
      - discovery-server
  product-service:
    build:
      context: ./product-service/
      dockerfile: Dockerfile
    ports:
      - 2222:2222
    depends_on:
      - configuration-server