version: "3.0"
services:
  discovery:
    build: 
      context: ./Discovery/
      dockerfile: Dockerfile
    ports:
      - 4444:4444
  gateway:
    build:
      context: ./Gateway/
      dockerfile: Dockerfile
    ports:
      - 5555:5555
    depends_on:
      - discovery