eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:4444/eureka/
    enabled: true
    registryFetchIntervalSeconds: 10
    instanceInfoReplicationIntervalSeconds: 10
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 20
