eureka:
  client:
    enabled: true
    registryFetchIntervalSeconds: 10
    instanceInfoReplicationIntervalSeconds: 10
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 20

description: "This is Dev env profile"
