server:
  port: 3333

spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: 'https://github.com/PalampurRockstar/Backend'
          clone-on-start: true
          search-paths: 'common-configuration/config_route_via_discovery_server/{profile}'

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:4444/eureka/