server:
  port: 5555

spring:
  application:
    name: Gateway

eureka:
  instance:
    hostname: localhost

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:4444/eureka/