server:
  port: 9004

spring:
  application:
    name: Gateway

#eureka:
#  instance:
#    hostname: localhost
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:9003/eureka/
#
eureka:
  instance:
    hostname: localhost

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9003/eureka/
#      defaultZone: http://${eureka.instance.hostname}:9003/eureka/